### ISSUE TITLE
When try run get_my_followers.py got error

### ISSUE THREAD

**Issue by alex37529** [MaximPiessen/instagram_network_analysis#1]
```
Traceback (most recent call last):
  File "get_my_followers.py", line 34, in <module>
    get_my_followers(config)
  File "get_my_followers.py", line 18, in get_my_followers
    b.login(username, password)
  File "/home/musicwarez/work/insta_download/visual/instagram_network_analysis/01 scraping/bot.py", line 42, in login
    self.driver.find_element_by_xpath("//button[contains(.,'Log In')]").click()
  File "/home/musicwarez/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/musicwarez/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/musicwarez/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/musicwarez/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//button[contains(.,'Log In')]"}
  (Session info: headless chrome=80.0.3987.122)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-48-generic x86_64)

```

**Comment by apbog** [comment]
Check that the instagram log in page is in English.
