### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by sinatmertens** [MaximPiessen/instagram_network_analysis#7]
Hey Maxim!

First thank you for that great documentation!
I tried to run your bot and everything went just fine so far but whenever I try to run you from_relations_to_json.py I get this:

Traceback (most recent call last):
  File "relations_to_json.py", line 83, in <module>
    relations_to_json(config)
  File "relations_to_json.py", line 55, in relations_to_json
    id_2 = name_to_id[accounts[1]]
KeyError: 'zackbumm_'

Account 2 is pretty much the followed account in the very first line, as if:
https://www.instagram.com/sina_tabea/ https://www.instagram.com/zackbumm_/

It's not about that particular account name, I tried to delete a row and I always get the same result.
I'm working on a mac and maybe it's something about the .txt formation? 

Thanks in advance!

**Comment by bymabe** [comment]
Hello, I have the same problem, did you find a solution ?
